// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOkoA2ZYKNI5IqjJk4HGN69u449OKg8W8',
    appId: '1:1088459541617:web:25c6c06311eaefac75dfd0',
    messagingSenderId: '1088459541617',
    projectId: 'fir-newoperation',
    authDomain: 'fir-newoperation.firebaseapp.com',
    storageBucket: 'fir-newoperation.appspot.com',
    measurementId: 'G-9YTQ48CXQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj-VjV_vD-mxwM03Gk0aZjH5EN0stuCYY',
    appId: '1:1088459541617:android:6816283fada20fec75dfd0',
    messagingSenderId: '1088459541617',
    projectId: 'fir-newoperation',
    storageBucket: 'fir-newoperation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWRqPdty5ccX7Zm5TVV_Ezy8rl0tHEhVM',
    appId: '1:1088459541617:ios:6c5b3e10cb501e7875dfd0',
    messagingSenderId: '1088459541617',
    projectId: 'fir-newoperation',
    storageBucket: 'fir-newoperation.appspot.com',
    iosBundleId: 'com.advanced.practiceAdvancedTopic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWRqPdty5ccX7Zm5TVV_Ezy8rl0tHEhVM',
    appId: '1:1088459541617:ios:54fd4221b3c6c4ef75dfd0',
    messagingSenderId: '1088459541617',
    projectId: 'fir-newoperation',
    storageBucket: 'fir-newoperation.appspot.com',
    iosBundleId: 'com.advanced.practiceAdvancedTopic.RunnerTests',
  );
}
